service: s3-file-uploader-darwin

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-west-1

plugins:
  - serverless-iam-roles-per-function

custom:
  fileUploadBucketName: ${self:service}-bucket-${self:provider.stage}

functions:
  s3FileUploader:
    handler: src/upload.handler
    name: s3-file-uploader
    description: darwinnnnn
    timeout: 60
    memorySize: 128
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "s3:*"
        Resource: arn:aws:s3:::${self:custom.fileUploadBucketName}/*
    environment:
      FILE_UPLOAD_BUCKETNAME: ${self:custom.fileUploadBucketName}

    events:
      - http:
          path: images
          method: POST
          cors: true
  s3VideoUploader:
    handler: src/videoUpload.handler
    name: s3-video-uploader
    description: darwinnnnn
    timeout: 60
    memorySize: 128
    iamRoleStatements:
      - Effect: Allow
        Action:
          - "s3:*"
        Resource: arn:aws:s3:::${self:custom.fileUploadBucketName}/*
    environment:
      FILE_UPLOAD_BUCKETNAME: ${self:custom.fileUploadBucketName}

    events:
      - http:
          path: videos
          method: POST
          cors: true

resources:
  Resources:
    FileBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.fileUploadBucketName}
        AccessControl: PublicRead
